baseURL = ""
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Learn R Journalism"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/r-journalism/learn-r-journalism/edit/master/content/"
  description = "Learn R Journalism"
  author = "Andrew Ba Tran"
  showVisitedLinks = true
  themeVariant = "mine"
  disableLanguageSwitchingButton = true
  disableSearch = true



[outputs]
#home = [ "HTML", "RSS", "JSON"]
#home = [ "HTML", "RSS"]
home = ["HTML"]

[Languages]
[Languages.en]
title = "Journalism with R"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> R Journalism Case Studies"
identifier = "hugodoc"
url = "https://r-journalism.com"
weight = 10

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/r-journalism/learn-r-journalism"
weight = 20




[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> About"
url = "https://learn.r-journalism.com/en/about"
weight = 30

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> Repo Github"
identifier = "ds"
url = "https://github.com/r-journalism/learn-r-journalism"
weight = 20

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> R Journalism Case Studies"
identifier = "hugodoc"
url = "https://r-journalism.com"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> About"
url = "https://learn.r-journalism.com/en/about"
weight = 30

